pub mod batch_file;
pub mod chd_mount;
pub mod chd_to_cue;
pub mod default_rom;
pub mod emulator_specific;
pub mod shortcut;
pub mod steam_launch;
pub mod store_launch;
pub mod strategy;
pub mod zip_extract;

pub use batch_file::BatchFileStrategy;
pub use chd_mount::ChdMountStrategy;
pub use chd_to_cue::ChdToCueStrategy;
pub use default_rom::DefaultRomStrategy;
pub use emulator_specific::EmulatorSpecificStrategy;
pub use shortcut::ShortcutStrategy;
pub use steam_launch::SteamLaunchStrategy;
pub use store_launch::StoreLaunchStrategy;
pub use strategy::{execute_launch, LaunchContext, LaunchResult, LaunchStrategy};
pub use zip_extract::ZipExtractStrategy;
