pub mod emulator_manager;
pub mod game_library;
pub mod config_manager;
pub mod coin_manager;
pub mod coin_hardware;
pub mod timer_manager;
pub mod operator_panel;
pub mod autoboot;
pub mod theme_manager;
pub mod game_state;
pub mod gpio_coins;
pub mod arduino_serial;

pub use emulator_manager::EmulatorManager;
pub use game_library::GameLibrary;
pub use config_manager::ConfigManager;
pub use coin_manager::{CoinManager, CoinState, CoinEvent};
pub use coin_hardware::{CoinHardwareExt, HardwareConfig, HardwareType, HardwareMonitor};
pub use timer_manager::{TimerManager, TimerStatus, TimerState};
pub use operator_panel::{OperatorPanel, AuthLevel, SessionStats, OperatorStats, SystemHealth};
pub use autoboot::AutobootManager;
pub use theme_manager::{ThemeManager, Theme, ThemeConfig};
pub use game_state::{GameStateManager, AppState};
pub use gpio_coins::{GPIOCoinDetector, GPIOConfig};
pub use arduino_serial::{ArduinoInterface, ArduinoConfig};
