pub mod emulator_manager;
pub mod emulator_monitor;
pub mod emulator_detector;
pub mod game_library;
pub mod config_manager;
pub mod coin_manager;
pub mod coin_hardware;
pub mod timer_manager;
pub mod operator_panel;
pub mod autoboot;
pub mod theme_manager;
pub mod game_state;
pub mod gpio_coins;
pub mod arduino_serial;
pub mod media_manager;
pub mod shader_manager;
pub mod network_manager;
pub mod scraper;
pub mod importer;
pub mod steam_importer;
pub mod hardware_scripting;
pub mod bezel_manager;
pub mod session_manager;
pub mod kiosk_config;
pub mod retroachievements;
pub mod tag_manager;
pub mod safe_quit;
pub mod script_hooks;
pub mod video_pipeline;
pub mod plugin_engine;
pub mod display_manager;

pub use bezel_manager::BezelManager;
pub use emulator_manager::EmulatorManager;
pub use emulator_monitor::EmulatorMonitor;
pub use emulator_detector::{EmulatorDetector, EmulatorInfo};
pub use game_library::GameLibrary;
pub use config_manager::{ConfigManager, SystemGameConfig, GameMode};
pub use coin_manager::{CoinManager, CoinState, CoinEvent};
pub use coin_hardware::{CoinHardwareExt, HardwareConfig, HardwareType, HardwareMonitor};
pub use timer_manager::{TimerManager, TimerStatus, TimerState};
pub use operator_panel::{OperatorPanel, AuthLevel, SessionStats, OperatorStats, SystemHealth};
pub use autoboot::AutobootManager;
pub use theme_manager::{ThemeManager, Theme, ThemeInfo, ThemeColors, WheelSettings, OverlaySettings};
pub use game_state::{GameStateManager, AppState};
pub use gpio_coins::{GPIOCoinDetector, GPIOConfig};
pub use arduino_serial::{ArduinoInterface, ArduinoConfig};
pub use media_manager::{MediaManager, MediaType, MediaFile, MediaLibrary, MediaStats};
pub use shader_manager::{ShaderManager, Shader, ShaderType, ShaderPreset};
pub use network_manager::{NetworkManager, CabinetInfo, NetworkRole};
pub use scraper::{GameScraper, ScrapedGameInfo};
pub use importer::UniversalImporter;
pub use hardware_scripting::{HardwareScriptEngine, HardwareEvent, HardwareAction, HardwareScript};
pub use session_manager::{SessionManager, SessionMode, SessionConfig, SessionState, SessionStatus, ArcadeConfig, TimedConfig};
